### ISSUE TITLE
Update SDK to netcore2.0 and net461

### ISSUE THREAD

**Issue by chrsadk** [Penneo/sdk-net#103]
With this change:

- .NET Framework 4.0 will no longer be supported.
- Minimum requirement for usage will be .NET Framework 4.6.1 or .NET Core 2.0.
- Newtonsoft.Json will be updated to 11.0.2
- RestSharp will be updated to 106.3.1
- NUnit will be updated to 3.10.1
- SDK version will be 2.0

**Comment by fabianbadoi** [comment]
This has been addressed in releases 3.0 and 4.0
