### ISSUE TITLE
RestSharp 107.x.x

### ISSUE THREAD

**Issue by ForeverFast** [Penneo/sdk-net#141]
Hello. Are there any plans to switch to "RestSharp 107.x.x" in the near future? I am working on a project using Penneo.SDK and RestSharp 107.2.1. After launching the project, I get the following message:

System.MissingMethodException: 'Method not found: 'Void RestSharp.RestClient.set_UserAgent(System.String)'.'

The problem is the difference in the versions used.

**Comment by HeadCookie** [comment]
Done RestSharp as [been added in 5.0.1](https://www.nuget.org/packages/Penneo.SDK/5.0.1#dependencies-body-tab)
