### ISSUE TITLE
Don't use .Result but do proper await

### ISSUE THREAD

**Issue by burningice2866** [Penneo/sdk-net#155]
Don't use .Result but do proper async await

https://github.com/Penneo/sdk-net/blob/ae2803c07e129f489facdd4d82c9d90178a272d8/Src/Penneo/RestConnector.cs#L36

**Comment by danneforslund** [comment]
This change is bound to make deadlocks happen when the SDK is called from UI threads, Blazor, etc. Please review, or as @burningice2866 said, implement proper Async()-methods throughout the whole SDK.

**Comment by danneforslund** [comment]
Much appreciated! 👍
