### ISSUE TITLE
How do enable drawing and upload of picture for a signer via the API

### ISSUE THREAD

**Issue by burningice2866** [Penneo/sdk-net#170]
How do enable drawing and upload of picture for a signer when creating cases and adding signers?

**Comment by HeadCookie** [comment]
There’s a bool to enable it on the signingRequest https://github.com/Penneo/sdk-net/blob/60bffe31d5ba19ce03dae39341fe3baba097c4ef/Src/Penneo/(Model)/SigningRequest.cs#L25C1-L26C1
And an enum to set specific types: https://github.com/Penneo/sdk-net/blob/60bffe31d5ba19ce03dae39341fe3baba097c4ef/Src/Penneo/(Model)/SigningRequest.cs#L26

**Comment by burningice2866** [comment]
Dear child has many names, as we would say in Danish. It used to be called Touch signature but I believe the term now-a-days is Simple Electronic Signature.

Is there any documentation about the different InsecureSigningMethods and what their string-values are?

**Comment by HeadCookie** [comment]
@burningice2866 We can agree on that 😅 At some point we'll probably re-name it to simple electronic signature everywhere, but that'll be in a major version. 

The [string values are here](https://github.com/Penneo/sdk-net/blob/60bffe31d5ba19ce03dae39341fe3baba097c4ef/Src/Penneo/(Model)/SigningRequest.cs#L64-L69):

```csharp
    public static class InsecureSigningMethod
    {
        public const string Draw = "draw";
        public const string Image = "image";
        public const string Text = "text";
    }
```

You can do something like 
```csharp
mySigningRequest.InsecureSigningMethods = new List<string> { InsecureSigningMethod.Draw, InsecureSigningMethod.Image };
```

**Comment by HeadCookie** [comment]
@burningice2866 Oh, and there's a some info on SES [in our help center (scroll down a bit)](https://penneo.my.site.com/support/s/article/Which-Signing-Methods-can-be-used?language=en_US)

**Comment by burningice2866** [comment]
@HeadCookie ah, `InsecureSigningMethods` was added in version 5.1.0. Im still stuck on 4.3.0 for the time being. But good to know its there when i get to upgrade.
