### ISSUE TITLE
Use of latest RestSharp version

### ISSUE THREAD

**Issue by THTHO** [Penneo/sdk-net#175]
Im unable to use RestSharp v. 110.2.0 (newest atm) in my projects.

I get runtime errors, like:

"System.MissingMethodException: Method not found: 'Void RestSharp.RestClient.set_UserAgent(System.String)'.\r\n   at Penneo.Connector.ApiConnector.Init()

Any plans of updating to newest RestSharp for this package?

**Comment by jpa-penneo** [comment]
@THTHO you should be able to use it now with the new version (7.0.0). Please let us know if you have any problem. 

Regards,

**Comment by HeadCookie** [comment]
Resolved with #176
