### ISSUE TITLE
How to manually send out validations

### ISSUE THREAD

**Issue by janflora** [Penneo/sdk-net#2]
If a customer chooses to send out a CPR validation not using the Penneo system to generate the emails, if someone tries to resend the validation from the web application, the result will be that the validation can't be send.

Investigate whether the email text and email subject can be set after the validation has been activated using the "send" method and the link has been extracted.

If this is possible, update the documentation to specify this as the default procedure when you want to handle email sending yourself.

**Comment by ahmadnazir** [comment]
This is the same as: https://github.com/Penneo/sdk-php/issues/1
