### ISSUE TITLE
Add methods for writing meta data as key/value pairs

### ISSUE THREAD

**Issue by janflora** [Penneo/sdk-net#20]
We should support methods for writing case file and document meta data as key/value pairs. This is just helper functions that will just convert data back and forward between native objects and JSON objects (to be stored as a string through the API).
We should be aware that the values can be binary so doing a base64 encode/decode should be mandatory.

**Comment by chrsadk** [comment]
@janflora 

Since the json objects will eventually be read by both sdks and the website, we need a common json format. Do you want to define that, or should i come up with the format?

By the way, do you really want to base64 encode everything? Or just binary data? (i.e. files and byte arrays supplied directly)

**Comment by janflora** [comment]
@chrsadk Meta data is meant to be customer specific. The only reason we are introducing these meta data methods is to aid our integration partners even more than we are already doing. So we should never use the customer meta data through our own UIs and therefore the specific format is not that important.

I was imagining encoding everything as a JSON object to implement a very simple key-value store. We don't necessarily have to base64 encode everything. If you create different methods for setting values you could create one taking a string as value, another taking a byte array and so forth.

It is fine if you just pick an approach you see fit. You're probably closer to the customers perspective than I am :-) The whole idea is that the customer can store additional data as easy as possible, supporting both strings and files.

And remember that we have meta data both on case file level and on document level.
