### ISSUE TITLE
Document options format has changed

### ISSUE THREAD

**Issue by janflora** [Penneo/sdk-net#28]
The "options" property of the document object has been deprecated in favor of the "opts" property. The "opts" property is real JSON.
Update the SDK to use the new property.

**Comment by chrsadk** [comment]
@janflora @ahmadnazir 

Is the format going to be

{"key1","value1","key2":"value2", ...}

or

[{"key1","value1"},{"key2","value2"}, ...]

**Comment by janflora** [comment]
@chrsadk The first one. The API is returning an empty array instead of an empty object if no options are set. We are looking into that.

**Comment by janflora** [comment]
@chrsadk The problem has been fixed now. So now we have the following:
If there is options data you have something like this:
{"key1","value1","key2":"value2", ...}
Else the "opts" key is not going to be there. Just like the old approach.

**Comment by chrsadk** [comment]
@janflora Where is it fixed? Sandbox is still giving opts:[]
