### ISSUE TITLE
Default value for sensitive data option

### ISSUE THREAD

**Issue by janflora** [Penneo/sdk-net#29]
The flag that determines whether a case file contains sensitive data can default to either set or unset at customer level. This default value is now readable through the API and should be used when creating a new case file object.

**Comment by chrsadk** [comment]
@janflora I can't find the appropiate url to call in the API (to get the default value for sensitive data)?

**Comment by janflora** [comment]
@chrsadk You have to fetch the customer object and that will contain the default value for the customer. If there's several customers mapped to the user, use the first one.
