### ISSUE TITLE
Why is SignatureLine.SignedAt not hydrated?

### ISSUE THREAD

**Issue by ahmadnazir** [Penneo/sdk-net#32]
I am trying to find out why the SignedAt value is not hydrated when we get a json response from the server.

If you look at:

https://github.com/Penneo/sdk-net/blob/master/Src/Penneo/(Model)/SignatureLine.cs#L46

.. could it be because we say `internal set` instead of just `set`?

**Comment by chrsadk** [comment]
@ahmadnazir Yes, it was because of the "internal" access. I have fixed it and created a pull request.
