### ISSUE TITLE
Assigning case file templates to case files

### ISSUE THREAD

**Issue by ahmadnazir** [Penneo/sdk-net#50]
I have been going through the documentation at for creating [casefiles](https://github.com/Penneo/sdk-net/blob/master/docs/templates.md#creating-a-case-file-from-a-template). However, I can see that the case file template is not persisted when the SetCaseFileTemplate() function is called:

```
// Create a new case file
var myCaseFile = new CaseFile();

// Get the case file templates available to the authenticated user
var availableTemplates = myCaseFile.GetTemplates().Objects;

// Assign the first list item as the case file template
myCaseFile.SetCaseFileTemplate(availableTemplates.First());
```

Can you please elaborate?

**Comment by chrsadk** [comment]
You also need the line

`var result = myCaseFile.Persist();`

where result is true or false.

If you need details about the result, you can call the following property after Persist:

`var detailResult = myCaseFile.LatestServerResult;`

**Comment by ahmadnazir** [comment]
I did persist the case file. It still doesn't work. I used the LatestServerResult to find out that `VisibilityMode` is not part of the mapping when the case file is being updated, and the API requires it to be present.

This is the json response that I get:

```
{"code":400,"message":"Validation Failed","errors":{"children":{"title":[],"metaData":[],"sendAt":[],"expireAt":[],"visibilityMode":{"errors":["This value should not be null."]},"caseFileTypeId":[],"sensitiveData":[],"reference":[]}}}
```

The API has always required the `visibilityMode` to be present for updates (even though the documentation doesn't say so). This just means that none of the sdk users are relying on the case file update functionality. Either the API or its documentation should be updated.

Nonetheless, I suggest that the sdk should allow the visibility mode to be updated as well.

**Comment by ahmadnazir** [comment]
@chrsadk Can you please look into this?

**Comment by chrsadk** [comment]
@ahmadnazir Sorry, i had not seen that the issue was converted from a question to a bug.

I am however not clear on which change you would like implemented? The initial part of the question is about creating a case file and the latter part is about visibility mode.

But I can see that you have made visibilitymode updatable in the php-sdk recently, so i'll do the same in the Net SDK now.

Let me know if you have an additional change in mind.
