### ISSUE TITLE
Rewrite unit tests

### ISSUE THREAD

**Issue by janflora** [Penneo/sdk-net#9]
Rewrite the unit tests in nUnit or xUnit.
This guide might be a good place to start http://approache.com/blog/from-mstest-to-nunit/

**Comment by chrsadk** [comment]
Fixed in fork

**Comment by ahmadnazir** [comment]
The unit tests still have dependencies on Microsoft specific libraries e.g. see line 7 in CaseFileTests.cs:

```
using Assert = Microsoft.VisualStudio.TestTools.UnitTesting.Assert;
```

We need another approach so that we can run the tests in mono.
