### ISSUE TITLE
RestSharp is not an dependency

### ISSUE THREAD

**Issue by mortenmoulder** [Penneo/sdk-net#95]
## Issue
I was getting this error first time I was making an API call (`.persist()`):

>Could not load type 'RestSharp.Authenticators.IAuthenticator'

I saw that `RestSharpSigned` was a dependency, but apparently that wasn't enough.

## Fix
Open the Nuget package manager and install the regular RestSharp  (not RestSharpSigned).

### Other
I would've created a pull request, but I'm not sure if removing RestSharpSigned would break anything.

**Comment by ahmadnazir** [comment]
Hi @mortenmoulder 

Thanks for reporting this. Can you see if this issue is fixed for you in release 1.6.0?

**Comment by fabianbadoi** [comment]
Issue fixed.
